version: '3.7'

services:
  db:
    image: postgres:latest
    restart: 'no'
    ports:
    - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev
  handler:
    build:
      context: .
      dockerfile: Dockerfile_handler
    command: "python data_service/data_handle_service/data_monitoring.py"
    volumes:
    - .:Data_handler/
    depends_on:
      - db
  app:
    build:
      context: .
      dockerfile: Dockerfile_app
    command: flask run --host=0.0.0.0
    volumes:
      - .:/Api/
    ports:
      - 5000:5000
    env_file:
      - .env.dev
    depends_on:
      - db

volumes:
  postgres_data: